version: '3.8'

services:
  vite:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app             # Monta código para hot reload
      - /app/node_modules  # Evita sobrescribir los node_modules del contenedor
    command: npm run dev
